# Generated by Django 4.2.6 on 2024-01-26 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_apps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='next_job_uuids',
            new_name='next_job_names',
        ),
        migrations.AlterField(
            model_name='job',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='job',
            unique_together={('workflow_uuid', 'name')},
        ),
    ]
