# Generated by Django 4.2.6 on 2024-02-05 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_apps', '0002_rename_next_job_uuids_job_next_job_names_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='completed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='status',
            field=models.CharField(choices=[('running', 'running'), ('success', 'success'), ('fail', 'fail')], default='running', max_length=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
