# Generated by Django 4.2.6 on 2024-01-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_apps', '0002_rename_next_job_uuids_job_next_job_names_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
