# Generated by Django 4.2.6 on 2024-02-23 16:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('project_apps', '0003_alter_history_completed_at_alter_history_started_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheduling',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workflow_uuid', models.UUIDField()),
                ('scheduled_at', models.CharField(max_length=100, null=True)),
                ('interval', models.CharField(max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
