# Generated by Django 4.2.6 on 2024-02-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_apps', '0004_scheduling'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduling',
            name='repeat_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scheduling',
            name='interval',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='scheduling',
            name='scheduled_at',
            field=models.DateTimeField(null=True),
        ),
    ]
