# Generated by Django 4.2.6 on 2024-02-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_apps', '0005_scheduling_repeat_count_alter_scheduling_interval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='retries',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='timeout',
            field=models.IntegerField(default=0),
        ),
    ]
