# Generated by Django 4.2.6 on 2024-03-01 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_apps', '0006_job_retries_job_timeout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduling',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
